### ISSUE TITLE
[Feature] Include rockspec and source shas in lockfile when building

### ISSUE THREAD

**Issue by mrcjkb** [nvim-neorocks/rocks#116]
I don't think we need it for lookups. But it's useful for integrity checks, in case someone force-uploaded a modified rockspec or source archive (which defeats the purpose of locking and is a supply chain vulnerability).
The benefit of this for Nix is that it can use a cached version if the source or rockspec hash has changed. We could one day implement something similar.
And if there's nothing in the cache and a mismatched rockspec/source hash, it would be reported as an error (with an option to update the lock entry, warning that it could be a supply chain attack).

_Originally posted by @mrcjkb in https://github.com/nvim-neorocks/rocks/pull/111#discussion_r1787622636_

**Comment by vhyrro** [comment]
> We don't need it for lookups

I'm currently implementing update functionality and I've started thinking about this again. An update command needs to remove the old version of a rock from the lockfile and replace it with the new, updated rock.

To know which entry to delete, it has to be able to derive the UID for the rock in the JSON. This is not feasible if the main hash already contains source and rockspec information. Is there something inherently wrong with the following, since you haven't mentioned any drawbacks?

```json
"<uid>": {
    "name": "neorg",
    "version": "0.8.0",
    "source-hash": "sha256-aa0a5bcd396f3b8e59fa9dd8059a06c3bf4952f48473214d96fc46895edb59f0",
    "dependencies": []
}
```

Yes, this means we have two hashes, but these both have their own uses. The UID hash is used to differentiate a rock based on name, version and pinning information. The source hash is used to validate the integrity of the rock itself. Wdyt?

**Comment by mrcjkb** [comment]
That's exactly what I had in mind (only with an additional `rockspec-hash` field).
